export default function PrivacyPolicy() {
  return (
    <div className="container mx-auto py-8 bg-background">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>

      <p className="text-white mb-4">
        Our Privacy Policy was last updated on <strong>19 Jan 2025</strong>.
      </p>

      <p className="text-white mb-4">
        At <strong>Bytegrove Technology Private Limited</strong>, one of our
        main priorities is the privacy of our visitors. This Privacy Policy
        document contains types of information that is collected and recorded by{' '}
        <strong>Bytegrove Technology Private Limited</strong> and how we use it.
      </p>

      <p className="text-white mb-4">
        If you have additional questions or require more information about our
        Privacy Policy, do not hesitate to contact us at{' '}
        <a
          href="mailto:Ashish.1999vns@gmail.com"
          className="text-blue-600 underline hover:text-blue-800"
        >
          Ashish.1999vns@gmail.com
        </a>
        .
      </p>

      <p className="text-white mb-4">
        This Privacy Policy applies only to our online activities and is valid
        for visitors to our website with regards to the information that they
        shared and/or collected on{' '}
        <a
          href="https://www.acecodinglab.com/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-600 underline hover:text-blue-800"
        >
          https://www.acecodinglab.com/
        </a>
        . This policy is not applicable to any information collected offline or
        via channels other than this website.
      </p>

      <h2 className="text-xl font-semibold text-white mb-4">Consent</h2>

      <p className="text-white mb-4">
        By using our website, you hereby consent to our Privacy Policy and agree
        to its terms.
      </p>

      <h2 className="text-xl font-semibold text-white mb-4">
        Information We Collect
      </h2>

      <p className="text-white mb-4">
        The personal information that you are asked to provide, and the reasons
        why you are asked to provide it, will be made clear to you at the point
        we ask you to provide your personal information. This policy has been
        generated by{' '}
        <a
          href="https://dodopayments.com"
          className="text-blue-600 underline hover:text-blue-800"
        >
          dodopayments.com
        </a>
        .
      </p>

      <p className="text-white mb-4">
        If you contact us directly, we may receive additional information about
        you such as your name, email address, phone number, the contents of the
        message and/or attachments you may send us, and any other information
        you may choose to provide.
      </p>

      <p className="text-white mb-4">
        When you register for an account, we may ask for your contact
        information, including items such as name, company name, address, email
        address, and telephone number.
      </p>

      <h2 className="text-xl font-semibold text-white mb-4">
        How We Use Your Information
      </h2>

      <p className="text-white mb-4">
        We use the information we collect in various ways, including to:
      </p>

      <ul className="list-disc pl-5 text-white mb-4">
        <li className="mb-2">Provide, operate, and maintain our website.</li>
        <li className="mb-2">Improve, personalize, and expand our website.</li>
        <li className="mb-2">
          Understand and analyze how you use our website.
        </li>
        <li className="mb-2">
          Develop new products, services, features, and functionality.
        </li>
        <li className="mb-2">
          Communicate with you, either directly or through one of our partners,
          including for customer service, to provide you with updates and other
          information relating to the website, and for marketing and promotional
          purposes.
        </li>
        <li className="mb-2">Send you emails.</li>
        <li className="mb-2">Find and prevent fraud.</li>
      </ul>

      <h2 className="text-xl font-semibold text-white mb-4">Log Files</h2>

      <p className="text-white mb-4">
        <strong>Bytegrove Technology Private Limited</strong> follows a standard
        procedure of using log files. These files log visitors when they visit
        websites. All hosting companies do this as part of hosting
        services&apos; analytics.
      </p>

      <p className="text-white mb-4">
        The information collected by log files includes internet protocol (IP)
        addresses, browser type, Internet Service Provider (ISP), date and time
        stamp, referring/exit pages, and possibly the number of clicks. These
        are not linked to any information that is personally identifiable. The
        purpose of the information is for analyzing trends, administering the
        site, tracking users&apos; movement on the website, and gathering
        demographic information.
      </p>

      <h2 className="text-xl font-semibold text-white mb-4">
        Cookies and Web Beacons
      </h2>

      <p className="text-white mb-4">
        Like any other website,{' '}
        <strong>Bytegrove Technology Private Limited</strong> uses
        &apos;cookies&apos;. These cookies are used to store information
        including visitors&apos; preferences, and the pages on the website that
        the visitor accessed or visited.
      </p>

      <p className="text-white mb-4">
        The information is used to optimize the users&apos; experience by
        customizing our web page content based on visitors&apos; browser type
        and/or other information.
      </p>

      <h2 className="text-xl font-semibold text-white mb-4">
        Advertising Partners Privacy Policies
      </h2>

      <p className="text-white mb-4">
        Third-party ad servers or ad networks use technologies like cookies,
        JavaScript, or Web Beacons that are used in their respective
        advertisements and links that appear on{' '}
        <strong>Bytegrove Technology Private Limited</strong>, which are sent
        directly to users&apos; browsers. They automatically receive your IP
        address when this occurs. These technologies are used to measure the
        effectiveness of their advertising campaigns and/or to personalize the
        advertising content that you see on websites that you visit.
      </p>

      <p className="text-white mb-4">
        Note that <strong>Bytegrove Technology Private Limited</strong> has no
        access to or control over these cookies that are used by third-party
        advertisers.
      </p>

      <h2 className="text-xl font-semibold text-white mb-4">
        Third Party Privacy Policies
      </h2>

      <p className="text-white mb-4">
        <strong>Bytegrove Technology Private Limited</strong>&apos;s Privacy
        Policy does not apply to other advertisers or websites. Thus, we are
        advising you to consult the respective Privacy Policies of these
        third-party ad servers for more detailed information. It may include
        their practices and instructions about how to opt-out of certain
        options.
      </p>

      <p className="text-white mb-4">
        You can choose to disable cookies through your individual browser
        options. This is recommended by dodopayments.com. To know more detailed
        information about cookie management with specific web browsers, it can
        be found at the browsers&apos; respective websites.
      </p>

      <h2 className="text-xl font-semibold text-white mb-4">
        CCPA Privacy Rights (Do Not Sell My Personal Information)
      </h2>

      <p className="text-white mb-4">
        Under the CCPA, among other rights, California consumers have the right
        to:
      </p>

      <ul className="list-disc pl-5 text-white mb-4">
        <li className="mb-2">
          Request that a business that collects a consumer&apos;s personal data
          disclose the categories and specific pieces of personal data that a
          business has collected about consumers.
        </li>
        <li className="mb-2">
          Request that a business delete any personal data about the consumer
          that a business has collected.
        </li>
        <li className="mb-2">
          Request that a business that sells a consumer&apos;s personal data,
          not sell the consumer&apos;s personal data.
        </li>
      </ul>

      <p className="text-white mb-4">
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us.
      </p>

      <h2 className="text-xl font-semibold text-white mb-4">
        GDPR Data Protection Rights
      </h2>

      <p className="text-white mb-4">
        We want to ensure you are fully aware of all of your data protection
        rights. Every user is entitled to the following:
      </p>

      <ul className="list-disc pl-5 text-white mb-4">
        <li className="mb-2">
          <strong>The right to access:</strong> You have the right to request
          copies of your personal data. We may charge you a small fee for this
          service.
        </li>
        <li className="mb-2">
          <strong>The right to rectification:</strong> You have the right to
          request that we correct any information you believe is inaccurate. You
          also have the right to request that we complete the information you
          believe is incomplete.
        </li>
        <li className="mb-2">
          <strong>The right to erasure:</strong> You have the right to request
          that we erase your personal data, under certain conditions.
        </li>
        <li className="mb-2">
          <strong>The right to restrict processing:</strong> You have the right
          to request that we restrict the processing of your personal data,
          under certain conditions.
        </li>
        <li className="mb-2">
          <strong>The right to object to processing:</strong> You have the right
          to object to our processing of your personal data, under certain
          conditions.
        </li>
        <li className="mb-2">
          <strong>The right to data portability:</strong> You have the right to
          request that we transfer the data that we have collected to another
          organization, or directly to you, under certain conditions.
        </li>
      </ul>

      <p className="text-white mb-4">
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us.
      </p>

      <h2 className="text-xl font-semibold text-white mb-4">
        Children&apos;s Information
      </h2>

      <p className="text-white mb-4">
        Another part of our priority is adding protection for children while
        using the internet. We encourage parents and guardians to observe,
        participate in, and/or monitor and guide their online activity. These
        guidelines have been generated by dodopayments.com.
      </p>

      <p className="text-white mb-4">
        <strong>Bytegrove Technology Private Limited</strong> does not knowingly
        collect any Personal Identifiable Information from children under the
        age of 13. If you think that your child provided this kind of
        information on our website, we strongly encourage you to contact us
        immediately and we will do our best efforts to promptly remove such
        information from our records.
      </p>
    </div>
  );
}
