export default function RefundPolicy() {
  return (
    <div className="container p-8 bg-background text-white mx-auto">
      <h1 className="text-3xl font-bold mb-4">Return & Refund Policy</h1>

      <p className="mb-4">
        Our Return and Refund Policy was last updated on{' '}
        <strong>19/01/2024</strong>.
      </p>

      <p className="mb-4">
        Thank you for shopping at{' '}
        <strong>Bytegrove Technology Private Limited</strong>.
      </p>

      <p className="mb-6">
        The following terms are applicable for any products that you have
        purchased from us.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Eligibility for Refunds</h2>

      <p className="mb-4">
        We offer refunds under the following circumstances:
      </p>

      <ul className="list-disc pl-6 mb-6">
        <li className="mb-2">
          If the service is not delivered as promised due to an error on our
          end.
        </li>
        <li className="mb-2">
          If a technical issue caused by our platform prevents you from
          accessing the features you paid for, and the issue cannot be resolved
          within a reasonable timeframe.
        </li>
        <li className="mb-2">
          If you cancel your subscription within the refund period outlined
          below.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">Refund Period</h2>

      <p className="mb-6">
        Refund requests must be made within <strong>7</strong> days of the
        payment date. Requests made after this period will not be eligible for a
        refund.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Non-Refundable Cases</h2>

      <p className="mb-4">
        Refunds will not be granted under the following conditions:
      </p>

      <ul className="list-disc pl-6 mb-6">
        <li className="mb-2">
          If you change your mind after purchasing a subscription or service.
        </li>
        <li className="mb-2">
          If you fail to use the service during the subscription period.
        </li>
        <li className="mb-2">
          If the issue is caused by third-party software or tools not affiliated
          with our platform.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">Refund Process</h2>

      <p className="mb-4">To request a refund, please follow these steps:</p>

      <ol className="list-decimal pl-6 mb-6">
        <li className="mb-2">
          Contact our support team at{' '}
          <a
            href="mailto:Ashish.1999vns@gmail.com"
            className="text-blue-400 underline"
          >
            Ashish.1999vns@gmail.com
          </a>
          .
        </li>
        <li className="mb-2">
          Provide your payment receipt, order ID, and a detailed explanation of
          the issue.
        </li>
        <li className="mb-2">
          Our team will review your request and respond within 3-5 business
          days.
        </li>
        <li className="mb-2">
          If your request is approved, the refund will be processed to your
          original payment method within 7-10 business days.
        </li>
      </ol>

      <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>

      <p className="mb-4">
        If you have any questions about this Refund Policy or require
        assistance, please reach out to us:
      </p>

      <p className="mb-6">
        Email:{' '}
        <a
          href="mailto:Ashish.1999vns@gmail.com"
          className="text-blue-400 underline"
        >
          Ashish.1999vns@gmail.com
        </a>
      </p>

      <p className="text-sm">
        This refund policy was generated by{' '}
        <a href="https://dodopayments.com" className="text-blue-400 underline">
          dodopayments.com
        </a>
        .
      </p>
    </div>
  );
}
