import { SideNavBar } from "@/components/ui/sideNav";
import { TooltipProvider } from "@/components/ui/tooltip";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="grid h-screen w-full pl-[56px]">
      <TooltipProvider >
        <SideNavBar />
        {children}
        </TooltipProvider>
      </div>
  );
}
